export const COMMON_VALUES = {
    QUOTATION_STATUS_INITIAL: 'INITIAL',
    QUOTATION_STATUS_REVISED: 'REVISED',
    QUOTATION_STATUS_REALISED: 'REALISED',
    LIFE_ASSURE_TYPE_1:'Life1',
    LIFE_ASSURE_TYPE_2: 'Life2',
    CUSTOMER_CARE_EMAIL: 'customer.care@hnbassurance.com',
    POLICY_FEE: 200,
    HNB_BANK_CODE: 1,
    DEFAULT_RI_COMPANY: 'MunichRe',

    COMMON_PWD: '1234',
    MIN_PWD_LENGTH: 4
};

// CUSTOMER_CARE_EMAIL:'customer.care@hnbassurance.com'